script:
- gem install bundler:2.0.1
- bundle update --bundler
- if [[ "${TRAVIS_COMMIT_MESSAGE}" =~ "New-Post" ]]; then export PUSH_NOTIFICATION="yes"; else export PUSH_NOTIFICATION="no"; fi

deploy:
  provider: pages
  fqdn: blog.geekofia.in
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  verbose: true
  script: ./scripts/new_post_push_message.sh $OPEN_SIGNAL_API $PUSH_NOTIFICATION
  on:
    branch: master

env:
  global:
  - secure: R1iIwbOUnHTT6IWpjwfhdNJ92YCMgC94yw0kz5eAHRoOSlEXKXV6BUYajnXJ9+Jrx7V9DY7hwa/WMMVY1aKdMHFmoCleK8rWNew6npLXGGsLcgBQgbsDNQ1Dlq4MoZP0KwtnE4c8Kyxe1604tkf4+R6o4Fg2rKxLxbQzEDPgHYhJDaZRTjJTCPqntoXieDgo8HQTjVhcsXKXnL7DPKYVeLe8AJGHZPhE1TJGsxI0FR8kFmcZwaPLNJnXmInxZmwAvLyzhnbkQl2lsV42wiukfT1Yz33FEP5Z4vGxcCbHLKLqKZFP4Wneus0wFxi7+PSCL8nPIyYoMq58qjl6bng3DBM4+qyv0/4wbTngB2NyyqixVEtJaNHlah7B1o3EpgNdq930SZiyFBnJzqVrPIO2fz+vIGS/C5s5zWTD27W2JeBdYqkSXTHRmcqTtk1Bkn5jRZlQ1jO3a0fkmwSH45xgzoN7chKHWYJazetxV4uAWMxOGg5GFyY70cMsQwwbmwfMzZKlUBa1PsWCdyzvPCNm68AsvaxtXwDhOPGBX8/Wa5Aj6Dah0x5daFeT6OVrPQBpgUOYlWfweQgTXD8JMz7tv9N8s+IYGkkZ1xa4LNz98uGexhiA/LR7zRhKdTI9hW9C28ggNVqcPpuVUw5nefFWhGntHurCU+Zy/EGGoH/pr38=
  - secure: efFguGATI0snmXoL0YGDpiNMjQskb2F9LcDpLGfKEGGj6vSLrPHw2o+Z3V5X8H5qwwoMF4lPYY4mO8UO1q4pCtdg5tB9v0LIdsGchHfMGjpX0CV4h22heJA/u3gQLjwccAEfIs/vHTkiDPev1TShTv3QFVzfOYBHnBgjXmqYGLkglonEunq4kW+vPaskARig1Hh5HUos0nSOFzTfWpOQmLCLPXcBglTD5ldeAnnhlZ8saBhfoyrMUVVDfdj2mBAQAh6Bpw/1Mg+Vel3xJiPjwkijT0w192u8RBLUrTnHYRUc3fGxL8ZwT6ifb5SPEDKZDYv2JBGCNRbIRBG/g5Sn/jtCnBiPIYLobyqlsCk97RZwu1OpE/AdIoV/bVn0SUi6hQCQcjbhBRcQxMeDPdZLuZzCrsqYG2oQwPkKFS4nKlXzlkLbb2fztGSpmxgMwtm1vMeM3mT/kQxq1zbJQCu2JCg0qk3n+5wz8zbiIPvmy+bU7dI24HLCVfifEda1JbGHYaCXBg0VyVK05rg/zb0pPXy5TPdWs62vjaza5YsQ4+2BTrazNg2aPVJEnAoKDXcQ8gddY9z7QnbZWXZ70zaYqRA8jZx0CSsDbUIgRAqbsaqt2Z0e12VHDlt72dfiujaPUm16rBv7g6pXR+m9OhDkME4FoClDjrhGtpOSO3dRC3U=
